<?php

namespace App\Models;

use App\Scopes\ContactSearchScope;
use App\Scopes\FilterScope;
use App\Scopes\SearchScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static factory()
 */
class Contact extends Model
{
    protected $fillable = ['first_name','last_name','email','phone','address','company_id'];

    public $filterColumns = ['company_id'];

    use HasFactory;
    public function company(){
    return $this->belongsTo(Company::class);
}

public function scopeLatestFirst($query){
        return $query->orderBy('id', 'desc');
}
//public function scopeFilter($query)
//{
//    if ($companyId = request('company_id')){
//        $query->where( 'company_id',$companyId ) ;
//
//    }
//    if ($search = request('search')){
//        $query->where('first_name' , 'LIKE' , "%{$search}%");
//    };
//
//    return $query;
//}

protected static function booted()
{
//    parent::booted(); // TODO: Change the autogenerated stub

    static::addGlobalScope(new FilterScope);
//    static::addGlobalScope(new SearchScope);
    static::addGlobalScope(new ContactSearchScope);

}
}
